---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ktranslate-config
data:
  snmp.yml: |
    devices: {}
    trap:
      listen: 0.0.0.0:1620
      community: {{ .Values.env.community }}
      version: ""
      transport: "" 
      v3_config: null
      trap_only: false
    discovery:
      cidrs:
      - 172.31.0.26/32
      ignore_list: []
      debug: false
      ports:
      - 161
      default_communities:
      - {{ .Values.env.community }}
      use_snmp_v1: false
      default_v3: null
      add_devices: true
      add_mibs: true
      threads: 4
      replace_devices: true
      kentik: null
    global:
      poll_time_sec: 300
      drop_if_outside_poll: false
      mib_profile_dir: /etc/ktranslate/profiles
      mibs_db: /etc/ktranslate/mibs.db
      mibs_enabled:
      - IF-MIB
      timeout_ms: 30000
      retries: 0
      global_v3: null
      response_time: false
      purge_devices_after_num: 0
      no_device_hardcoded_oids: false
      user_tags: {}
      match_attributes: {}
      providers: {}
      jitter_time_sec: 0
      fast_poll: false
