---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ktranslate-config
data:
  snmp.yml: |
    devices: {}
    trap:
      listen: 0.0.0.0:1620
    discovery:
      cidrs:
      - 172.31.2.18/32
      ignore_list: []
      debug: false
      ports:
      - 161
      default_communities:
      - public
      default_v3: null
      add_devices: true
      add_mibs: true
      threads: 4
      replace_devices: true
      check_all_ips: true
    global:
      poll_time_sec: 300
      mib_profile_dir: /etc/ktranslate/profiles
      mibs_enabled:
      - IF-MIB
      timeout_ms: 3000
      retries: 0