---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktranslate
spec:
  selector:
    matchLabels:
      app: ktranslate
  template:
    metadata:
      labels:
        app: ktranslate
    spec:
      initContainers:
      - name: copy-configmap
        image: docker.io/kentik/ktranslate:v2.1.22
        command: ["/bin/sh", "-c", "cp /etc/ktranslate/snmp.yml /data"]
        volumeMounts:
          - name: ktranslate-config
            mountPath: /etc/ktranslate/snmp.yml
            subPath: snmp.yml
          - name: empty-dir-volume
            mountPath: /data
          - name: ktranslate-config-claim
            mountPath: /etc/ktranslate/profiles
      containers:
      - name: ktranslate
        image: docker.io/kentik/ktranslate:v2.1.22
        imagePullPolicy: Always
        env:
        - name: NEW_RELIC_API_KEY
          value: {{ .Values.env.nr_api_key | quote }}
        - name: NR_ACCOUNT_ID
          value: {{ .Values.env.nr_account_id | quote}}
        - name: NR_REGION
          value: "EU"
        args:
          - --metalisten=0.0.0.0:8083
          - --snmp=/data/snmp.yml
          - --metrics=jchf
          - --tee_logs=true
          - --snmp_discovery_on_start=true
          - --snmp_discovery_min=10
          - --nr_region=EU
          - --log_level=debug
          - nr1.snmp
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - name: metadata
          containerPort: 8083
        - name: snmp
          containerPort: 1620
          hostPort: 162
          protocol: UDP
        livenessProbe:
          httpGet:
            path: /metrics
            port: metadata
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metadata
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: ktranslate-config
            mountPath: /etc/ktranslate/snmp.yml
            subPath: snmp.yml
          - name: empty-dir-volume
            mountPath: /data
          - name: ktranslate-config-claim
            mountPath: /etc/ktranslate/profiles
      volumes:
        - name: ktranslate-config
          configMap:
            name: ktranslate-config
        - name : empty-dir-volume
          emptyDir: {}
        - name: ktranslate-config-claim
          hostPath:
            path: /mnt/data
