apiVersion: v1
kind: Service
metadata:
  name: ktranslate-metadata
  labels:
    app: ktranslate
spec:
  ports:
  - port: 8083
    name: metadata
    targetPort: 8083
    protocol: TCP
  selector:
    app: ktranslate
---
apiVersion: v1
kind: Service
metadata:
  name: ktranslate-snmp
  labels:
    app: ktranslate
spec:
  ports:
  - port: 162
    name: snmp
    targetPort: 1620
    protocol: UDP
  selector:
    app: ktranslate
  type: NodePort
