apiVersion: v1
kind: Service
metadata:
  name: ktranslate-metadata
  labels:
    app: ktranslate
spec:
  ports:
  - port: 8083
    name: metadata
    targetPort: 8083
    protocol: TCP
  selector:
    app: ktranslate

---
apiVersion: v1
kind: Service
metadata:
  name: ktranslate-snmp
  labels:
    app: ktranslate
spec:
  ports:
  - port: 162
    name: snmp
    targetPort: 1620
    protocol: UDP
  selector:
    app: ktranslate
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ktranslate-config-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ktranslate-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
